/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package GUI;

import BUS.NguoiDungBUS;
import DTO.NguoiDungDTO;
import java.awt.Cursor;
import javax.swing.ImageIcon;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.SwingUtilities;

/**
 *
 * @author Tuong Vy Ha
 */
public class DangKiGUI extends javax.swing.JPanel {

    NguoiDungBUS ndBUS = new NguoiDungBUS();

    /**
     * Creates new form DangNhapGUI
     */
    public DangKiGUI() {
        initComponents();
        controls();
    }

    public void controls() {
        btnDangKy.setCursor(new Cursor(Cursor.HAND_CURSOR));
        btnXemMatKhau.setIcon(new ImageIcon(getClass().getResource("/images/eye-icon.png")));
        btnXemMatKhau1.setIcon(new ImageIcon(getClass().getResource("/images/eye-icon.png")));
    }
    
    private void hienThiDangNhap(){
        DangNhapGUI dnGUI = new DangNhapGUI();
        JFrame frame = new JFrame("Đăng nhập");
        frame.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        frame.add(dnGUI);
        frame.pack();
        frame.setLocationRelativeTo(null);
        frame.setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lblDangKi = new javax.swing.JLabel();
        lblTenDN = new javax.swing.JLabel();
        lblMK = new javax.swing.JLabel();
        txtHoTen = new javax.swing.JTextField();
        txtNhapLaiMK = new javax.swing.JPasswordField();
        btnDangKy = new javax.swing.JButton();
        lblEmail = new javax.swing.JLabel();
        txtMK = new javax.swing.JPasswordField();
        lblNhapLaiMK = new javax.swing.JLabel();
        lblHoTen = new javax.swing.JLabel();
        txtEmail = new javax.swing.JTextField();
        txtTenDN = new javax.swing.JTextField();
        btnXemMatKhau = new javax.swing.JButton();
        btnXemMatKhau1 = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 255));

        jPanel1.setBackground(new java.awt.Color(0, 153, 153));
        jPanel1.setForeground(java.awt.Color.white);

        lblDangKi.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblDangKi.setForeground(java.awt.Color.white);
        lblDangKi.setText("Đăng kí");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblDangKi)
                .addGap(205, 205, 205))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(lblDangKi)
                .addContainerGap(23, Short.MAX_VALUE))
        );

        lblTenDN.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblTenDN.setText("Tên đăng nhập:");

        lblMK.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblMK.setText("Mật khẩu:");

        txtHoTen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtHoTenActionPerformed(evt);
            }
        });

        txtNhapLaiMK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNhapLaiMKActionPerformed(evt);
            }
        });

        btnDangKy.setBackground(new java.awt.Color(0, 153, 153));
        btnDangKy.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnDangKy.setForeground(java.awt.Color.white);
        btnDangKy.setText("Đăng kí");
        btnDangKy.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDangKyActionPerformed(evt);
            }
        });

        lblEmail.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblEmail.setText("Email:");

        txtMK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtMKActionPerformed(evt);
            }
        });

        lblNhapLaiMK.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblNhapLaiMK.setText("Nhập lại mật khẩu:");

        lblHoTen.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblHoTen.setText("Họ và tên:");

        txtEmail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtEmailActionPerformed(evt);
            }
        });

        txtTenDN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTenDNActionPerformed(evt);
            }
        });

        btnXemMatKhau.setBackground(new java.awt.Color(0, 153, 153));
        btnXemMatKhau.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        btnXemMatKhau.setForeground(java.awt.Color.white);
        btnXemMatKhau.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnXemMatKhau.setRolloverEnabled(false);
        btnXemMatKhau.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXemMatKhauActionPerformed(evt);
            }
        });

        btnXemMatKhau1.setBackground(new java.awt.Color(0, 153, 153));
        btnXemMatKhau1.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        btnXemMatKhau1.setForeground(java.awt.Color.white);
        btnXemMatKhau1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnXemMatKhau1.setRolloverEnabled(false);
        btnXemMatKhau1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXemMatKhau1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblMK)
                    .addComponent(lblTenDN)
                    .addComponent(lblNhapLaiMK)
                    .addComponent(lblHoTen)
                    .addComponent(lblEmail))
                .addGap(36, 36, 36)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnDangKy, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(txtNhapLaiMK, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(btnXemMatKhau1, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(txtMK, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(btnXemMatKhau, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(txtTenDN)
                        .addComponent(txtHoTen)
                        .addComponent(txtEmail)))
                .addContainerGap(30, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(35, 35, 35)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(lblTenDN)
                                            .addComponent(txtTenDN, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(39, 39, 39)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                .addComponent(lblMK)
                                                .addComponent(txtMK, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addComponent(btnXemMatKhau, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(67, 67, 67))
                                    .addComponent(btnXemMatKhau1, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(lblNhapLaiMK)
                                .addComponent(txtNhapLaiMK, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(67, 67, 67))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtHoTen, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lblHoTen)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 37, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblEmail))
                .addGap(48, 48, 48)
                .addComponent(btnDangKy, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(48, 48, 48))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void txtNhapLaiMKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNhapLaiMKActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNhapLaiMKActionPerformed

    private void btnDangKyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDangKyActionPerformed
        String hoTen = txtHoTen.getText();
        String tenDN = txtTenDN.getText();
        String email = txtEmail.getText();
        String matKhau = new String(txtMK.getPassword());
        String nhapLaiMK = new String(txtNhapLaiMK.getPassword());

        if (hoTen.isEmpty() || tenDN.isEmpty() || email.isEmpty() || matKhau.isEmpty() || nhapLaiMK.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Vui lòng điền đầy đủ thông tin.", "Lỗi", JOptionPane.ERROR_MESSAGE);
            return;
        }

        if (tenDN.length() < 6 || tenDN.length() > 20) {
            JOptionPane.showMessageDialog(this, "Tên đăng nhập phải từ 6 đến 20 ký tự.", "Lỗi", JOptionPane.ERROR_MESSAGE);
            return;
        }

        if (!tenDN.matches("^[a-zA-Z0-9_]+$")) {
            JOptionPane.showMessageDialog(this, "Tên đăng nhập chỉ được chứa ký tự chữ và số.", "Lỗi", JOptionPane.ERROR_MESSAGE);
            return;
        }
        
        if (ndBUS.kiemTraTrungTenDangNhap(tenDN)) {
            JOptionPane.showMessageDialog(this, "Tên đăng nhập đã được đăng ký.", "Lỗi", JOptionPane.ERROR_MESSAGE);
            return;
        }

        if (matKhau.length() < 6 || matKhau.length() > 20) {
            JOptionPane.showMessageDialog(this, "Mật khẩu phải từ 6 đến 20 ký tự.", "Lỗi", JOptionPane.ERROR_MESSAGE);
            return;
        }

        if (!matKhau.equals(nhapLaiMK)) {
            JOptionPane.showMessageDialog(this, "Mật khẩu không khớp.", "Lỗi", JOptionPane.ERROR_MESSAGE);
            return;
        }

        if (!email.matches("^[\\w-\\.]+@([\\w-]+\\.)+[\\w-]{2,4}$")) {
            JOptionPane.showMessageDialog(this, "Email không hợp lệ.", "Lỗi", JOptionPane.ERROR_MESSAGE);
            return;
        }

        if (ndBUS.kiemTraTrungEmail(email)) {
            JOptionPane.showMessageDialog(this, "Email đã được đăng ký.", "Lỗi", JOptionPane.ERROR_MESSAGE);
            return;
        }

        NguoiDungDTO ndDTO = new NguoiDungDTO();
        ndDTO.setHoTen(hoTen);
        ndDTO.setTenDN(tenDN);
        ndDTO.setEmail(email);
        ndDTO.setMatKhau(matKhau);

        if (ndBUS.dangKyUser(ndDTO)) {
            JOptionPane.showMessageDialog(this, "Đăng kí thành công!", "Thành công", JOptionPane.INFORMATION_MESSAGE);
            JFrame parentFrame = (JFrame) SwingUtilities.getWindowAncestor(this);
            parentFrame.dispose();
            hienThiDangNhap();
        } else {
            JOptionPane.showMessageDialog(this, "Đăng kí thất bại. Vui lòng thử lại.", "Lỗi", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnDangKyActionPerformed

    private void txtHoTenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtHoTenActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtHoTenActionPerformed

    private void txtMKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtMKActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtMKActionPerformed

    private void txtEmailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtEmailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtEmailActionPerformed

    private void txtTenDNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTenDNActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTenDNActionPerformed

    private void btnXemMatKhauActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXemMatKhauActionPerformed
        if (txtMK.getEchoChar() != '\u0000') {
            txtMK.setEchoChar('\u0000'); // Show the password
        } else {
            txtMK.setEchoChar((Character) javax.swing.UIManager.get("PasswordField.echoChar")); // Hide the password
        }
    }//GEN-LAST:event_btnXemMatKhauActionPerformed

    private void btnXemMatKhau1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXemMatKhau1ActionPerformed
        if (txtNhapLaiMK.getEchoChar() != '\u0000') {
            txtNhapLaiMK.setEchoChar('\u0000'); // Show the password
        } else {
            txtNhapLaiMK.setEchoChar((Character) javax.swing.UIManager.get("PasswordField.echoChar")); // Hide the password   
        }
    }//GEN-LAST:event_btnXemMatKhau1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDangKy;
    private javax.swing.JButton btnXemMatKhau;
    private javax.swing.JButton btnXemMatKhau1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblDangKi;
    private javax.swing.JLabel lblEmail;
    private javax.swing.JLabel lblHoTen;
    private javax.swing.JLabel lblMK;
    private javax.swing.JLabel lblNhapLaiMK;
    private javax.swing.JLabel lblTenDN;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtHoTen;
    private javax.swing.JPasswordField txtMK;
    private javax.swing.JPasswordField txtNhapLaiMK;
    private javax.swing.JTextField txtTenDN;
    // End of variables declaration//GEN-END:variables
}
