/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package GUI;

import BUS.CauHoiBUS;
import BUS.ChuDeBUS;
import BUS.DangNhapBUS;
import BUS.KetQuaBUS;
import DTO.KetQuaDTO;
import java.awt.Color;
import java.awt.Cursor;
import java.awt.Dimension;
import java.awt.Font;
import java.util.ArrayList;
import java.util.Vector;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Thu Huyền
 */
public class PnDanhSachKetQuaGUI extends javax.swing.JPanel {
    
    DefaultTableModel modelKetQua = new DefaultTableModel();
    Font font = new Font("Tahoma", Font.BOLD, 13);
    CauHoiBUS chBUS = new CauHoiBUS() ;
    ChuDeBUS cdBUS = new ChuDeBUS();
    KetQuaBUS kqBUS = new KetQuaBUS();
    DangNhapBUS dnBUS = new DangNhapBUS();
    private int userID = dnBUS.nguoidungLogin.getMaND();

    /**
     * Creates new form PnDanhSachKetQua
     */
    public PnDanhSachKetQuaGUI() {
        initComponents();
        loadDanhSachLenBang(userID);
        controls();
        
    }
    

    public void controls(){
        modelKetQua = new DefaultTableModel();
        // Thêm các cột vào model
        modelKetQua.addColumn("Mã bài thi");
        modelKetQua.addColumn("Ngày thi");
        modelKetQua.addColumn("Điểm số");
        
        // Gán model cho bảng
        tblDSKQ.setModel(modelKetQua);

        // layout bảng
        tblDSKQ.setFocusable(false);
        tblDSKQ.setIntercellSpacing(new Dimension(0, 0));
        tblDSKQ.getTableHeader().setFont(font);
        tblDSKQ.setRowHeight(40);
        tblDSKQ.setShowVerticalLines(false);
        tblDSKQ.getTableHeader().setOpaque(false);
        tblDSKQ.setFillsViewportHeight(true);
        tblDSKQ.getTableHeader().setBackground(new Color(0, 153, 153));
        tblDSKQ.getTableHeader().setForeground(Color.WHITE);
        tblDSKQ.setSelectionBackground(new Color(232, 232, 232));
        tblDSKQ.setCursor(new Cursor(Cursor.HAND_CURSOR));

        int id = dnBUS.nguoidungLogin.getMaND();
        loadDanhSachLenBang(id);
    }
    
    public void loadDanhSachLenBang(int userID){
        kqBUS.doclistkq();
        ArrayList<KetQuaDTO> dskq = kqBUS.getListKetQuaTheoID(userID);
        System.out.println(dskq);
        loadDataLenBangCauHoi(dskq);
    }
    
    
    public void loadDataLenBangCauHoi(ArrayList<KetQuaDTO> ds){
        modelKetQua.setRowCount(0);
        if (ds != null) {
            for (KetQuaDTO kq : ds) {
                Vector vec = new Vector();
                vec.add(kq.getExCode());
                vec.add(kq.getDate());
                vec.add(kq.getRs_mask());
                modelKetQua.addRow(vec);
            }
        } else {
            System.out.println("Danh sach cau hoi là null.");
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tblDSKQ = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        btnReset = new javax.swing.JButton();

        tblDSKQ.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tblDSKQ);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("LỊCH SỬ LÀM BÀI");

        btnReset.setBackground(new java.awt.Color(0, 153, 153));
        btnReset.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnReset.setForeground(java.awt.Color.white);
        btnReset.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/reset-icon.png"))); // NOI18N
        btnReset.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnReset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnResetActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnReset, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(328, 328, 328))
            .addGroup(layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 941, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel1)
                    .addComponent(btnReset, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 459, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(135, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnResetActionPerformed
        int id = dnBUS.nguoidungLogin.getMaND();
        loadDanhSachLenBang(id);
    }//GEN-LAST:event_btnResetActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnReset;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblDSKQ;
    // End of variables declaration//GEN-END:variables
}
