/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package GUI;

import BUS.BaiThiBUS;
import BUS.CauHoiBUS;
import BUS.ChuDeBUS;
import BUS.DangNhapBUS;
import BUS.DeThiBUS;
import DTO.BaiThiDTO;
import DTO.ChuDeDTO;
import java.awt.BorderLayout;
import java.awt.Cursor;
import java.awt.Font;
import java.util.ArrayList;
import java.util.Random;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Thu Huyền
 */
public class PnLamBaiThiGUI extends javax.swing.JPanel {

    DangNhapBUS dnBUS = new DangNhapBUS();
    BaiThiBUS btBUS = new BaiThiBUS();
    DeThiBUS dtBUS = new DeThiBUS();
    private int remainingAttempts;

    /**
     * Creates new form PnLamBaiThi
     */
    public PnLamBaiThiGUI() {
        initComponents();
        controls();
    }

    public void controls() {
        txtuserID.setText(dnBUS.nguoidungLogin.getHoTen());
        txtuserID.setEditable(false);

        btnThi.setCursor(new Cursor(Cursor.HAND_CURSOR));

        loadCmbBaiThi();
    }

//    public void loadCmbBaiThi() {
//        cmbMaDe.removeAllItems();
//        ArrayList<String> dsbt = btBUS.getListBaithi();
//        for (String bt : dsbt) {
//            cmbMaDe.addItem(bt);
//        }
//    }
    public void loadCmbBaiThi() {
        btBUS.docdanhsach();
        cmbMaDe.removeAllItems();
        ArrayList<BaiThiDTO> dsbt = new ArrayList<>();
        dsbt = btBUS.getListBaiThi();
        cmbMaDe.addItem("0 - Chọn bài thi");
        for (BaiThiDTO bt : dsbt) {
            cmbMaDe.addItem(bt.getTestCode() + " - " + bt.getTestTitle());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelThongTin = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtuserID = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        cmbMaDe = new javax.swing.JComboBox<>();
        btnThi = new javax.swing.JButton();
        jPanelThi = new javax.swing.JPanel();

        jPanelThongTin.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel1.setText("Xin chào người dùng: ");

        txtuserID.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setText("Chọn mã đề thi: ");

        cmbMaDe.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        cmbMaDe.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        btnThi.setBackground(new java.awt.Color(0, 153, 153));
        btnThi.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnThi.setForeground(java.awt.Color.white);
        btnThi.setText("Thi ngay");
        btnThi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThiActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelThongTinLayout = new javax.swing.GroupLayout(jPanelThongTin);
        jPanelThongTin.setLayout(jPanelThongTinLayout);
        jPanelThongTinLayout.setHorizontalGroup(
            jPanelThongTinLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelThongTinLayout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtuserID, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cmbMaDe, javax.swing.GroupLayout.PREFERRED_SIZE, 256, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnThi, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(35, Short.MAX_VALUE))
        );
        jPanelThongTinLayout.setVerticalGroup(
            jPanelThongTinLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelThongTinLayout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addGroup(jPanelThongTinLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtuserID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(cmbMaDe, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnThi))
                .addContainerGap(19, Short.MAX_VALUE))
        );

        jPanelThi.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        javax.swing.GroupLayout jPanelThiLayout = new javax.swing.GroupLayout(jPanelThi);
        jPanelThi.setLayout(jPanelThiLayout);
        jPanelThiLayout.setHorizontalGroup(
            jPanelThiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanelThiLayout.setVerticalGroup(
            jPanelThiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 326, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jPanelThongTin, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(jPanelThi, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanelThongTin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanelThi, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnThiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThiActionPerformed

        String testCodeodd = (String) cmbMaDe.getSelectedItem();
        String testCode = testCodeodd.substring(0, 8);

        // Kiểm tra nếu không tìm thấy giá trị testCode
        if (testCode == null) {
            JOptionPane.showMessageDialog(this, "Không tìm thấy mã đề thi");
            return;
        }

        // Lấy exCode từ testCode
        ArrayList<String> exCodes = dtBUS.getExCodesByTestCode(testCode);

        // Kiểm tra nếu không tìm thấy mã bài thi (exCode)
        if (exCodes.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Không tìm thấy mã bài thi cho mã đề thi này.");
            return;
        }

        // Lấy exCode ngẫu nhiên từ danh sách exCodes
        Random rand = new Random();
        String exCode = exCodes.get(rand.nextInt(exCodes.size()));

        // Lấy testLimit từ testCode
        int testLimit = dtBUS.getTestLimitByTestCode(testCode);

        // Kiểm tra nếu không tìm thấy giá trị testLimit
        if (testLimit == -1) {
            JOptionPane.showMessageDialog(this, "Không tìm thấy giới hạn số lượt thi cho mã đề thi này.");
            return;
        }

        // Lấy userID từ thông tin người dùng đăng nhập
        int userID = dnBUS.nguoidungLogin.getMaND(); // Gán giá trị userID khi đăng nhập

        // Lấy tổng số lần thi đã thực hiện từ bảng result
        int totalAttempts = dtBUS.getTotalAttemptsByTestCode(testCode, userID);

        // Tính số lần thi còn lại
        remainingAttempts = testLimit - totalAttempts;

        remainingAttempts = Math.max(0, remainingAttempts);

        // Kiểm tra nếu số lần làm bài còn lại bằng 0 hoặc ít hơn
        if (remainingAttempts == 0) {
            JOptionPane.showMessageDialog(this, "Bạn đã hết số lượt thi");
            return; // Không cho phép thi nếu số lần thi bằng 0 hoặc ít hơn
        }

        // Lấy danh sách câu hỏi theo testCode
        ArrayList<String> dsbaithi = btBUS.getDeThiTheoTestCode(testCode);
        String deThiNgauNhien = dsbaithi.get(rand.nextInt(dsbaithi.size()));

        int time = (Integer.parseInt(btBUS.getTestTimeTheoTestCode(testCode))) * 60;

        PnlLamBaiThi dnGUI = new PnlLamBaiThi(deThiNgauNhien, time, remainingAttempts);
        // Tạo JFrame mới chứa JPanel PnThi
        jPanelThi.removeAll();
        jPanelThi.setLayout(new BorderLayout());
        jPanelThi.add(dnGUI, BorderLayout.CENTER);
        jPanelThi.revalidate();
        jPanelThi.repaint();
        btnThi.setEnabled(false);

    }//GEN-LAST:event_btnThiActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static javax.swing.JButton btnThi;
    public static javax.swing.JComboBox<String> cmbMaDe;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanelThi;
    private javax.swing.JPanel jPanelThongTin;
    private javax.swing.JTextField txtuserID;
    // End of variables declaration//GEN-END:variables
}
