/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package GUI;

import BUS.ThongKeBUS;
import DAO.MyConnect;
import java.awt.Color;
import java.awt.Cursor;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.time.LocalDate;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.Map;
import java.util.Vector;
import javax.swing.BorderFactory;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JTable;
import javax.swing.ListSelectionModel;
import javax.swing.SwingConstants;
import javax.swing.SwingUtilities;
import javax.swing.border.Border;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableCellRenderer;

/**
 *
 * @author HP
 */
public class PnThongKeGUI extends javax.swing.JPanel {

    ThongKeBUS thongkeBUS = new ThongKeBUS();
    ;

    /**
     * Creates new form PnThongKeGUI
     */
    LocalDate now = LocalDate.now();
    int year = now.getYear();
    DefaultTableModel model;

    public PnThongKeGUI() {
        initComponents();
        customizeComponents();
        loadDanhSachNam();
        updateThongKeTongQuat();
        

    }

    private void updateThongKeTongQuat() {

        baithi.setText("    Bài thi :   " + thongkeBUS.getBaiThiTheoNam(year));
        Slduthi.setText("   Số lượng dự thi :   " + thongkeBUS.getSLDuThiTheoNam(year));
        SLdat.setText("    Số lượng đạt (>=50%) :   " + thongkeBUS.getSLDatTheoNam(year));
        SLkodat.setText("   Số lượng không đạt :    " + thongkeBUS.getSLRotTheoNam(year));

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Slduthi = new javax.swing.JLabel();
        btnDetail = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        SLkodat = new javax.swing.JLabel();
        baithi = new javax.swing.JLabel();
        SLdat = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableThongKe = new javax.swing.JTable();

        setBackground(new java.awt.Color(255, 255, 255));
        setLayout(null);

        Slduthi.setBackground(new java.awt.Color(0, 153, 153));
        Slduthi.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        Slduthi.setForeground(new java.awt.Color(255, 255, 255));
        Slduthi.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        Slduthi.setToolTipText("");
        Slduthi.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        Slduthi.setOpaque(true);
        add(Slduthi);
        Slduthi.setBounds(570, 160, 360, 90);

        btnDetail.setBackground(new java.awt.Color(0, 153, 153));
        btnDetail.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnDetail.setForeground(new java.awt.Color(255, 255, 255));
        btnDetail.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnDetail.setText("Thống kê chi tiết");
        btnDetail.setToolTipText("");
        btnDetail.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        btnDetail.setOpaque(true);
        add(btnDetail);
        btnDetail.setBounds(0, 0, 230, 50);

        jLabel4.setBackground(new java.awt.Color(0, 153, 153));
        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Năm : ");
        jLabel4.setToolTipText("");
        jLabel4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jLabel4.setOpaque(true);
        add(jLabel4);
        jLabel4.setBounds(650, 70, 70, 40);

        jLabel6.setBackground(new java.awt.Color(255, 255, 255));
        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("THỐNG KÊ TỔNG QUÁT");
        jLabel6.setOpaque(true);
        add(jLabel6);
        jLabel6.setBounds(360, 60, 270, 50);

        SLkodat.setBackground(new java.awt.Color(0, 153, 153));
        SLkodat.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        SLkodat.setForeground(new java.awt.Color(255, 255, 255));
        SLkodat.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        SLkodat.setToolTipText("");
        SLkodat.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        SLkodat.setOpaque(true);
        add(SLkodat);
        SLkodat.setBounds(570, 300, 360, 90);

        baithi.setBackground(new java.awt.Color(0, 153, 153));
        baithi.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        baithi.setForeground(new java.awt.Color(255, 255, 255));
        baithi.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        baithi.setToolTipText("");
        baithi.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        baithi.setOpaque(true);
        add(baithi);
        baithi.setBounds(80, 160, 370, 90);

        SLdat.setBackground(new java.awt.Color(0, 153, 153));
        SLdat.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        SLdat.setForeground(new java.awt.Color(255, 255, 255));
        SLdat.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        SLdat.setToolTipText("");
        SLdat.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        SLdat.setOpaque(true);
        add(SLdat);
        SLdat.setBounds(80, 300, 370, 90);

        jComboBox1.setBackground(new java.awt.Color(0, 153, 153));
        jComboBox1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jComboBox1.setForeground(new java.awt.Color(255, 255, 255));
        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jComboBox1.setAutoscrolls(true);
        jComboBox1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jComboBox1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jComboBox1.setName(""); // NOI18N
        jComboBox1.setOpaque(true);
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });
        add(jComboBox1);
        jComboBox1.setBounds(720, 70, 110, 40);

        jTableThongKe.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTableThongKe.setGridColor(new java.awt.Color(0, 0, 0));
        jTableThongKe.setSelectionBackground(new java.awt.Color(204, 204, 204));
        jTableThongKe.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jScrollPane1.setViewportView(jTableThongKe);

        add(jScrollPane1);
        jScrollPane1.setBounds(80, 440, 850, 110);
    }// </editor-fold>//GEN-END:initComponents

    public void hienThiThongKe(int nam) {
        HashMap<Integer, Integer> duLieuBaiThi = thongkeBUS.layDuLieuBaiThi(nam);
        HashMap<Integer, Integer> duLieuDuThi = thongkeBUS.layDuLieuDuThi(nam);
        HashMap<Integer, Integer> duLieuDat = thongkeBUS.layDuLieuDat(nam);
        HashMap<Integer, Integer> duLieuRot = thongkeBUS.layDuLieuRot(nam);

        // Chuẩn bị dữ liệu cho từng dòng
        Object[][] data = new Object[4][13]; // 4 dòng, 13 cột (1 cột đầu là tên dòng)
        data[0][0] = "Bài thi";
        data[1][0] = "Dự thi";
        data[2][0] = "Đạt";
        data[3][0] = "Không đạt";

        for (int i = 1; i <= 12; i++) {
            data[0][i] = duLieuBaiThi.getOrDefault(i, 0);
            data[1][i] = duLieuDuThi.getOrDefault(i, 0);
            data[2][i] = duLieuDat.getOrDefault(i, 0);
            data[3][i] = duLieuRot.getOrDefault(i, 0);
        }

        // Tên cột
        String[] columnNames = {"", "Tháng 1", "Tháng 2", "Tháng 3", "Tháng 4", "Tháng 5", "Tháng 6",
            "Tháng 7", "Tháng 8", "Tháng 9", "Tháng 10", "Tháng 11", "Tháng 12"};

        // Cập nhật mô hình bảng
        jTableThongKe.setModel(new javax.swing.table.DefaultTableModel(data, columnNames));
        // Căn giữa nội dung trong các ô
        DefaultTableCellRenderer centerRenderer = new DefaultTableCellRenderer();
        centerRenderer.setHorizontalAlignment(SwingConstants.CENTER);
        for (int i = 0; i < jTableThongKe.getColumnCount(); i++) {
            jTableThongKe.getColumnModel().getColumn(i).setCellRenderer(centerRenderer);
        }

        // Đổi màu và căn giữa tiêu đề
        DefaultTableCellRenderer headerRenderer = new DefaultTableCellRenderer();
        headerRenderer.setHorizontalAlignment(SwingConstants.CENTER);
        headerRenderer.setBackground(new Color(0, 153, 153)); 
        headerRenderer.setForeground(Color.WHITE);     
        for (int i = 0; i < jTableThongKe.getColumnCount(); i++) {
            jTableThongKe.getColumnModel().getColumn(i).setHeaderRenderer(headerRenderer);
        }
    }

    private void customizeComponents() {
        btnDetail.setCursor(Cursor.getPredefinedCursor(Cursor.HAND_CURSOR));
        btnDetail.addMouseListener(new java.awt.event.MouseAdapter() {
            @Override
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnDetailMouseClicked(evt);
            }
        });
            }



    private void btnDetailMouseClicked(java.awt.event.MouseEvent evt) {
  JFrame parentFrame = (JFrame) SwingUtilities.getWindowAncestor(this);
    if (parentFrame != null) {
        // Ẩn giao diện chính
        parentFrame.setVisible(false);
    }

  
    PnThongkeGUIdetail detail = new PnThongkeGUIdetail();
    JFrame detailFrame = new JFrame("Chi tiết thống kê");
    detailFrame.add(detail);
    detailFrame.pack();
    detailFrame.setSize(850, 650);
    detailFrame.setLocationRelativeTo(null);
    detailFrame.setResizable(false);
   
    detailFrame.addWindowListener(new java.awt.event.WindowAdapter() {
        @Override
        public void windowClosing(java.awt.event.WindowEvent e) {
            if (parentFrame != null) {
                parentFrame.setVisible(true);
            }
        }
    });

    detailFrame.setVisible(true);
    }

  

    private void loadDanhSachNam() {
        // Lấy danh sách năm từ BUS
        ArrayList<Integer> danhSachNam = thongkeBUS.getDanhSachNam();

        // Đổ dữ liệu vào ComboBox
        jComboBox1.removeAllItems();
        for (Integer nam : danhSachNam) {
            jComboBox1.addItem(nam.toString());
        }
    }

    public void xuLyChonNam() {
        String selected = jComboBox1.getSelectedItem() + "";
        try {
            int nam = Integer.parseInt(selected);
            baithi.setText("    Bài thi :   " + thongkeBUS.getBaiThiTheoNam(nam));
            Slduthi.setText("   Số lượng dự thi :   " + thongkeBUS.getSLDuThiTheoNam(nam));
            SLdat.setText("    Số lượng đạt (>=50%) :   " + thongkeBUS.getSLDatTheoNam(nam));
            SLkodat.setText("   Số lượng không đạt :    " + thongkeBUS.getSLRotTheoNam(nam));
            hienThiThongKe(nam);
        } catch (Exception e) {
        }
    }
    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        // TODO add your handling code here:
        jComboBox1.setCursor(new Cursor(Cursor.HAND_CURSOR));
        jComboBox1.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                xuLyChonNam();
            }
        });
        jComboBox1.addActionListener(e -> {
            int nam = Integer.parseInt(jComboBox1.getSelectedItem().toString());

        });
    }//GEN-LAST:event_jComboBox1ActionPerformed



    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel SLdat;
    private javax.swing.JLabel SLkodat;
    private javax.swing.JLabel Slduthi;
    private javax.swing.JLabel baithi;
    private javax.swing.JLabel btnDetail;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableThongKe;
    // End of variables declaration//GEN-END:variables
}
