/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package GUI;

import BUS.NguoiDungBUS;
import DTO.NguoiDungDTO;
import java.awt.Cursor;
import java.util.ArrayList;
import java.util.Vector;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Thu Huyền
 */
public class SuaNguoiDungGUI extends javax.swing.JPanel {
        
        NguoiDungBUS ndBUS = new NguoiDungBUS();
        NguoiDungDTO nd = new NguoiDungDTO();
    /**
     * Creates new form ThemNguoiDung
     */
    public SuaNguoiDungGUI() {
        initComponents();
        controls();
        loadCmbVaiTro();
    }
    
    
    public void setThongTinNguoiDung(NguoiDungDTO nd) {
        txtMaND.setText(String.valueOf(nd.getMaND()));
        txtTenDN.setText(nd.getTenDN());
        txtTenDN.setEditable(false);
        txtMatKhau.setText(nd.getMatKhau());
        txtHoTen.setText(nd.getHoTen());
        txtEmail.setText(nd.getEmail());
        String vaiTro = nd.getVaiTro().equals("1") ? "Admin" : "User";
        cmbVaiTro.setSelectedItem(vaiTro);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTextPane1 = new javax.swing.JTextPane();
        jPanel1 = new javax.swing.JPanel();
        lblSuaND = new javax.swing.JLabel();
        txtMaND = new javax.swing.JTextField();
        txtTenDN = new javax.swing.JTextField();
        txtMatKhau = new javax.swing.JTextField();
        txtEmail = new javax.swing.JTextField();
        txtHoTen = new javax.swing.JTextField();
        lblMaND2 = new javax.swing.JLabel();
        lblTenDN2 = new javax.swing.JLabel();
        lblMatKhau2 = new javax.swing.JLabel();
        lblHoTen2 = new javax.swing.JLabel();
        lblVaiTro2 = new javax.swing.JLabel();
        lblEmail2 = new javax.swing.JLabel();
        btnSuaND = new javax.swing.JButton();
        cmbVaiTro = new javax.swing.JComboBox<>();

        jScrollPane1.setViewportView(jTextPane1);

        setBackground(new java.awt.Color(255, 255, 255));

        jPanel1.setBackground(new java.awt.Color(0, 153, 153));

        lblSuaND.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblSuaND.setForeground(java.awt.Color.white);
        lblSuaND.setText("SỬA NGƯỜI DÙNG");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(136, Short.MAX_VALUE)
                .addComponent(lblSuaND)
                .addGap(120, 120, 120))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblSuaND)
                .addContainerGap(7, Short.MAX_VALUE))
        );

        txtMaND.setEditable(false);
        txtMaND.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtMaNDActionPerformed(evt);
            }
        });

        txtTenDN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTenDNActionPerformed(evt);
            }
        });

        txtMatKhau.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtMatKhauActionPerformed(evt);
            }
        });

        txtEmail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtEmailActionPerformed(evt);
            }
        });

        txtHoTen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtHoTenActionPerformed(evt);
            }
        });

        lblMaND2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblMaND2.setText("Mã người dùng:");

        lblTenDN2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblTenDN2.setText("Tên đăng nhập:");

        lblMatKhau2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblMatKhau2.setText("Mật khẩu:");

        lblHoTen2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblHoTen2.setText("Họ tên:");

        lblVaiTro2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblVaiTro2.setText("Vai trò:");

        lblEmail2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblEmail2.setText("Email:");

        btnSuaND.setBackground(new java.awt.Color(0, 153, 153));
        btnSuaND.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnSuaND.setForeground(java.awt.Color.white);
        btnSuaND.setText("Sửa người dùng");
        btnSuaND.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSuaNDActionPerformed(evt);
            }
        });

        cmbVaiTro.setEditable(true);
        cmbVaiTro.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                            .addGap(34, 34, 34)
                            .addComponent(lblMaND2))
                        .addGroup(layout.createSequentialGroup()
                            .addGap(33, 33, 33)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(lblVaiTro2)
                                .addComponent(lblEmail2)
                                .addComponent(lblHoTen2))
                            .addGap(16, 16, 16)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblMatKhau2)
                            .addComponent(lblTenDN2))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtMaND, javax.swing.GroupLayout.DEFAULT_SIZE, 204, Short.MAX_VALUE)
                    .addComponent(txtTenDN)
                    .addComponent(txtMatKhau)
                    .addComponent(txtHoTen)
                    .addComponent(txtEmail)
                    .addComponent(cmbVaiTro, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(41, 41, 41))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnSuaND)
                .addGap(140, 140, 140))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 18, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtMaND, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblMaND2))
                .addGap(19, 19, 19)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTenDN2)
                    .addComponent(txtTenDN, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblMatKhau2)
                    .addComponent(txtMatKhau, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtHoTen, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblHoTen2))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblEmail2))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblVaiTro2)
                    .addComponent(cmbVaiTro, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addComponent(btnSuaND, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(23, 23, 23))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void txtMaNDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtMaNDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtMaNDActionPerformed

    private void txtMatKhauActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtMatKhauActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtMatKhauActionPerformed

    private void txtHoTenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtHoTenActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtHoTenActionPerformed

    private void txtTenDNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTenDNActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTenDNActionPerformed

    private void btnSuaNDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSuaNDActionPerformed
        String id = txtMaND.getText();
        String user = txtTenDN.getText();
        String email = txtEmail.getText();
        String pass = txtMatKhau.getText();
        String name = txtHoTen.getText();
        String vaitro = (String) cmbVaiTro.getSelectedItem();
        int vaitro1 = vaitro.equals("Admin") ? 1 : 0;

        if ( email.isEmpty() || name.isEmpty() || pass.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Không được để trống các trường");
            return;
        } else {
            boolean flag1 = checkEmail(email);
            if (flag1 != true) {
                JOptionPane.showMessageDialog(this, "Email phải đúng định dạng");
                return;
            } else {
                nd.setMaND(Integer.parseInt(id));
                nd.setTenDN(user);
                nd.setEmail(email);
                nd.setMatKhau(pass);
                nd.setHoTen(name);
                nd.setVaiTro(String.valueOf(vaitro1));
                boolean flag = ndBUS.updateNguoiDung(nd);

                if (flag) {
                    JOptionPane.showMessageDialog(this, "Cập nhật thông tin người dùng thành công");
                } else {
                    JOptionPane.showMessageDialog(this, "Cập nhật thông tin người dùng thất bại ");
                }
            }
        }
    }//GEN-LAST:event_btnSuaNDActionPerformed

    public void loadCmbVaiTro() {
        ArrayList<String> dsVaiTro = ndBUS.getVaiTro();

        cmbVaiTro.removeAllItems();  // Xóa các item cũ trong combo box

        for (String vaitro : dsVaiTro) {
            String vaiTro = vaitro.equals("1") ? "Admin" : "User";
            cmbVaiTro.addItem(vaiTro);
        }
    }
    
    public boolean checkEmail(String email) {
        String emailRegex = "^[a-zA-Z0-9._%+-]+@[a-zA-Z0-9.-]+\\.[a-zA-Z]{2,}$";
        Pattern pattern = Pattern.compile(emailRegex);
        Matcher matcher = pattern.matcher(email);
        return matcher.matches();
    }
    
    private void txtEmailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtEmailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtEmailActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSuaND;
    private javax.swing.JComboBox<String> cmbVaiTro;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextPane jTextPane1;
    private javax.swing.JLabel lblEmail2;
    private javax.swing.JLabel lblHoTen2;
    private javax.swing.JLabel lblMaND2;
    private javax.swing.JLabel lblMatKhau2;
    private javax.swing.JLabel lblSuaND;
    private javax.swing.JLabel lblTenDN2;
    private javax.swing.JLabel lblVaiTro2;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtHoTen;
    private javax.swing.JTextField txtMaND;
    private javax.swing.JTextField txtMatKhau;
    private javax.swing.JTextField txtTenDN;
    // End of variables declaration//GEN-END:variables

    public void controls(){
        btnSuaND.setCursor(new Cursor(Cursor.HAND_CURSOR));
    }
}
