/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package GUI;

import BUS.NguoiDungBUS;
import DTO.NguoiDungDTO;
import java.awt.Cursor;
import java.util.ArrayList;
import java.util.Vector;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Thu Huyền
 */
public class ThemNguoiDungGUI extends javax.swing.JPanel {
    
    NguoiDungDTO nd = new NguoiDungDTO();
    NguoiDungBUS ndBUS = new NguoiDungBUS();

    /**
     * Creates new form ThemNguoiDung
     */
    public ThemNguoiDungGUI() {
        initComponents();
        controls();
        loadCmbVaiTro();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTextPane1 = new javax.swing.JTextPane();
        jPanel1 = new javax.swing.JPanel();
        lblThemND = new javax.swing.JLabel();
        txtMaND1 = new javax.swing.JTextField();
        txtTenDN = new javax.swing.JTextField();
        txtMatKhau = new javax.swing.JTextField();
        txtEmail = new javax.swing.JTextField();
        txtHoTen = new javax.swing.JTextField();
        lblMaND1 = new javax.swing.JLabel();
        lblTenDN1 = new javax.swing.JLabel();
        lblMatKhau1 = new javax.swing.JLabel();
        lblHoTen1 = new javax.swing.JLabel();
        lblVaiTro1 = new javax.swing.JLabel();
        lblEmail1 = new javax.swing.JLabel();
        btnThemND = new javax.swing.JButton();
        cmbVaiTro = new javax.swing.JComboBox<>();

        jScrollPane1.setViewportView(jTextPane1);

        setBackground(new java.awt.Color(255, 255, 255));

        jPanel1.setBackground(new java.awt.Color(0, 153, 153));

        lblThemND.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblThemND.setForeground(java.awt.Color.white);
        lblThemND.setText("THÊM NGƯỜI DÙNG");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(130, Short.MAX_VALUE)
                .addComponent(lblThemND)
                .addGap(112, 112, 112))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblThemND)
                .addContainerGap())
        );

        txtMaND1.setEditable(false);
        txtMaND1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtMaND1ActionPerformed(evt);
            }
        });

        txtTenDN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTenDNActionPerformed(evt);
            }
        });

        txtMatKhau.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtMatKhauActionPerformed(evt);
            }
        });

        txtEmail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtEmailActionPerformed(evt);
            }
        });

        txtHoTen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtHoTenActionPerformed(evt);
            }
        });

        lblMaND1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblMaND1.setText("Mã người dùng:");

        lblTenDN1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblTenDN1.setText("Tên đăng nhập:");

        lblMatKhau1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblMatKhau1.setText("Mật khẩu:");

        lblHoTen1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblHoTen1.setText("Họ tên:");

        lblVaiTro1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblVaiTro1.setText("Vai trò:");

        lblEmail1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblEmail1.setText("Email:");

        btnThemND.setBackground(new java.awt.Color(0, 153, 153));
        btnThemND.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnThemND.setForeground(java.awt.Color.white);
        btnThemND.setText("Thêm người dùng");
        btnThemND.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThemNDActionPerformed(evt);
            }
        });

        cmbVaiTro.setEditable(true);
        cmbVaiTro.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cmbVaiTro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbVaiTroActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblMaND1)
                    .addComponent(lblTenDN1)
                    .addComponent(lblVaiTro1)
                    .addComponent(lblEmail1)
                    .addComponent(lblHoTen1)
                    .addComponent(lblMatKhau1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtMaND1, javax.swing.GroupLayout.DEFAULT_SIZE, 204, Short.MAX_VALUE)
                    .addComponent(txtTenDN)
                    .addComponent(txtMatKhau)
                    .addComponent(txtHoTen)
                    .addComponent(txtEmail)
                    .addComponent(cmbVaiTro, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(41, 41, 41))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnThemND)
                .addGap(132, 132, 132))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtMaND1, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblMaND1))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtTenDN, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblTenDN1))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtMatKhau, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblMatKhau1))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtHoTen, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblHoTen1))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblEmail1)
                    .addComponent(txtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblVaiTro1)
                    .addComponent(cmbVaiTro, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addComponent(btnThemND, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void txtMaND1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtMaND1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtMaND1ActionPerformed

    private void txtMatKhauActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtMatKhauActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtMatKhauActionPerformed

    private void txtHoTenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtHoTenActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtHoTenActionPerformed

    private void txtTenDNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTenDNActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTenDNActionPerformed

    private void btnThemNDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThemNDActionPerformed
        // TODO add your handling code here:
        NguoiDungBUS ndBUS = new NguoiDungBUS();

        String user = txtTenDN.getText();
        String email = txtEmail.getText();
        String pass = txtMatKhau.getText();
        String name = txtHoTen.getText();
        String vaitro = (String) cmbVaiTro.getSelectedItem();
        int vaitro1 = vaitro.equals("Admin") ? 1 : 0;

        if (user.isEmpty() || email.isEmpty() || name.isEmpty() || pass.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Không được để trống các trường");
            return;
        } else {
            boolean flag1 = checkEmail(email);
            if (flag1 != true) {
                JOptionPane.showMessageDialog(this, "Email phải đúng định dạng");
                return;
            } else {
                boolean flag2 = checkTenDangNhap(user);
                if (flag2 != true) {
                    JOptionPane.showMessageDialog(this, "Tên đăng nhập đã tồn tại trong hệ thống vui lòng thử lại tên mới");
                    return;
                } else {
                    nd.setTenDN(user);
                    nd.setEmail(email);
                    nd.setMatKhau(pass);
                    nd.setHoTen(name);
                    nd.setVaiTro(String.valueOf(vaitro1));
                    boolean flag = ndBUS.addNguoiDung(nd);

                    if (flag) {
                        JOptionPane.showMessageDialog(this, "Thêm người dùng thành công");
                    } else {
                        JOptionPane.showMessageDialog(this, "Thêm người dùng thất bại ");
                    }
                }
            }
        }

    }//GEN-LAST:event_btnThemNDActionPerformed

    private void txtEmailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtEmailActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_txtEmailActionPerformed

    private void cmbVaiTroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbVaiTroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbVaiTroActionPerformed

    public void loadCmbVaiTro() {
        ArrayList<String> dsVaiTro = ndBUS.getVaiTro();

        cmbVaiTro.removeAllItems();  // Xóa các item cũ trong combo box

        for (String vaitro : dsVaiTro) {
            String vaiTro = vaitro.equals("1") ? "Admin" : "User";
            cmbVaiTro.addItem(vaiTro);
        }
    }

    public boolean checkEmail(String email) {
        String emailRegex = "^[a-zA-Z0-9._%+-]+@[a-zA-Z0-9.-]+\\.[a-zA-Z]{2,}$";
        Pattern pattern = Pattern.compile(emailRegex);
        Matcher matcher = pattern.matcher(email);
        return matcher.matches();
    }
    
    public boolean checkTenDangNhap(String user){
        ArrayList<String> dsTenDangNhap = ndBUS.getListTenDangNhap();
            for(String username : dsTenDangNhap){
                if(username.contains(user)){
                    return false;
                }
            }
            return true;
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnThemND;
    private javax.swing.JComboBox<String> cmbVaiTro;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextPane jTextPane1;
    private javax.swing.JLabel lblEmail1;
    private javax.swing.JLabel lblHoTen1;
    private javax.swing.JLabel lblMaND1;
    private javax.swing.JLabel lblMatKhau1;
    private javax.swing.JLabel lblTenDN1;
    private javax.swing.JLabel lblThemND;
    private javax.swing.JLabel lblVaiTro1;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtHoTen;
    private javax.swing.JTextField txtMaND1;
    private javax.swing.JTextField txtMatKhau;
    private javax.swing.JTextField txtTenDN;
    // End of variables declaration//GEN-END:variables
    
    public void controls(){
        btnThemND.setCursor(new Cursor(Cursor.HAND_CURSOR));
    }
}
