/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package GUI;

import DTO.DeThiDTO;
import DTO.NguoiDungDTO;

/**
 *
 * @author Tuong Vy Ha
 */
public class XemDeThiGUI extends javax.swing.JPanel {

    /**
     * Creates new form ThemNguoiDung
     */
    public XemDeThiGUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTextPane1 = new javax.swing.JTextPane();
        txtMaND3 = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        lblXemDT = new javax.swing.JLabel();
        txtMaDT = new javax.swing.JTextField();
        txtMaCode = new javax.swing.JTextField();
        txtTenDeThi = new javax.swing.JTextField();
        txtChuDe = new javax.swing.JTextField();
        txtThoiGianLamBai = new javax.swing.JTextField();
        lblMaDT = new javax.swing.JLabel();
        lblMaCode = new javax.swing.JLabel();
        lblTenDeThi = new javax.swing.JLabel();
        lblThoiGianLamBai = new javax.swing.JLabel();
        lblSoLanThi = new javax.swing.JLabel();
        lblChuDe = new javax.swing.JLabel();
        cmbTinhTrang = new javax.swing.JComboBox<>();
        txtNgayTao = new javax.swing.JTextField();
        lblTinhTrang = new javax.swing.JLabel();
        txtSoLanThi = new javax.swing.JTextField();
        lblNgayTao = new javax.swing.JLabel();
        lblKho = new javax.swing.JLabel();
        lblDe = new javax.swing.JLabel();
        lblTB = new javax.swing.JLabel();
        txtTB = new javax.swing.JTextField();
        txtDe = new javax.swing.JTextField();
        txtKho = new javax.swing.JTextField();

        jScrollPane1.setViewportView(jTextPane1);

        txtMaND3.setEditable(false);
        txtMaND3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtMaND3ActionPerformed(evt);
            }
        });

        setBackground(new java.awt.Color(255, 255, 255));

        jPanel1.setBackground(new java.awt.Color(0, 153, 153));

        lblXemDT.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblXemDT.setForeground(java.awt.Color.white);
        lblXemDT.setText("XEM ĐỀ THI");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblXemDT)
                .addGap(163, 163, 163))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblXemDT)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        txtMaDT.setEditable(false);
        txtMaDT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtMaDTActionPerformed(evt);
            }
        });

        txtMaCode.setEditable(false);
        txtMaCode.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtMaCodeActionPerformed(evt);
            }
        });

        txtTenDeThi.setEditable(false);
        txtTenDeThi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTenDeThiActionPerformed(evt);
            }
        });

        txtChuDe.setEditable(false);
        txtChuDe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtChuDeActionPerformed(evt);
            }
        });

        txtThoiGianLamBai.setEditable(false);
        txtThoiGianLamBai.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtThoiGianLamBaiActionPerformed(evt);
            }
        });

        lblMaDT.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblMaDT.setText("Mã đề thi:");

        lblMaCode.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblMaCode.setText("Mã code:");

        lblTenDeThi.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblTenDeThi.setText("Tên đề thi:");

        lblThoiGianLamBai.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblThoiGianLamBai.setText("Thời gian làm bài:");

        lblSoLanThi.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblSoLanThi.setText("Số lần thi: ");

        lblChuDe.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblChuDe.setText("Chủ đề:");

        cmbTinhTrang.setEditable(true);
        cmbTinhTrang.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cmbTinhTrang.setEnabled(false);
        cmbTinhTrang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbTinhTrangActionPerformed(evt);
            }
        });

        txtNgayTao.setEditable(false);
        txtNgayTao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNgayTaoActionPerformed(evt);
            }
        });

        lblTinhTrang.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblTinhTrang.setText("Tình trạng:");

        txtSoLanThi.setEditable(false);
        txtSoLanThi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSoLanThiActionPerformed(evt);
            }
        });

        lblNgayTao.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblNgayTao.setText("Ngày tạo: ");

        lblKho.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblKho.setText("Khó: ");

        lblDe.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblDe.setText("Dễ: ");

        lblTB.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblTB.setText("Trung bình:");

        txtTB.setEditable(false);
        txtTB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTBActionPerformed(evt);
            }
        });

        txtDe.setEditable(false);
        txtDe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDeActionPerformed(evt);
            }
        });

        txtKho.setEditable(false);
        txtKho.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtKhoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblMaDT)
                    .addComponent(lblMaCode)
                    .addComponent(lblSoLanThi)
                    .addComponent(lblChuDe)
                    .addComponent(lblThoiGianLamBai)
                    .addComponent(lblTenDeThi)
                    .addComponent(lblNgayTao)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(lblDe)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(txtDe, javax.swing.GroupLayout.PREFERRED_SIZE, 1, Short.MAX_VALUE))
                        .addComponent(lblTinhTrang, javax.swing.GroupLayout.Alignment.LEADING)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblTB)
                        .addGap(18, 18, 18)
                        .addComponent(txtTB, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(40, 40, 40)
                        .addComponent(lblKho)
                        .addGap(18, 18, 18)
                        .addComponent(txtKho, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(txtNgayTao, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtMaDT, javax.swing.GroupLayout.DEFAULT_SIZE, 204, Short.MAX_VALUE)
                            .addComponent(txtMaCode)
                            .addComponent(txtTenDeThi)
                            .addComponent(txtThoiGianLamBai)
                            .addComponent(txtChuDe)
                            .addComponent(cmbTinhTrang, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtSoLanThi, javax.swing.GroupLayout.Alignment.TRAILING))))
                .addGap(41, 41, 41))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblMaDT)
                    .addComponent(txtMaDT, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtMaCode, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblMaCode))
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTenDeThi)
                    .addComponent(txtTenDeThi, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblThoiGianLamBai)
                    .addComponent(txtThoiGianLamBai, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtChuDe, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblChuDe))
                .addGap(17, 17, 17)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblSoLanThi)
                    .addComponent(txtSoLanThi, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtNgayTao, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblNgayTao))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 28, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblKho)
                    .addComponent(lblTB)
                    .addComponent(txtTB, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblDe)
                    .addComponent(txtDe, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtKho, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cmbTinhTrang, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblTinhTrang))
                .addGap(32, 32, 32))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void txtMaDTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtMaDTActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtMaDTActionPerformed

    private void txtTenDeThiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTenDeThiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTenDeThiActionPerformed

    private void txtThoiGianLamBaiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtThoiGianLamBaiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtThoiGianLamBaiActionPerformed

    private void txtMaCodeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtMaCodeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtMaCodeActionPerformed

    private void txtChuDeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtChuDeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtChuDeActionPerformed

    private void cmbTinhTrangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbTinhTrangActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbTinhTrangActionPerformed

    private void txtNgayTaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNgayTaoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNgayTaoActionPerformed

    private void txtSoLanThiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSoLanThiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSoLanThiActionPerformed

    private void txtTBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTBActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTBActionPerformed

    private void txtDeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDeActionPerformed

    private void txtMaND3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtMaND3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtMaND3ActionPerformed

    private void txtKhoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtKhoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtKhoActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> cmbTinhTrang;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextPane jTextPane1;
    private javax.swing.JLabel lblChuDe;
    private javax.swing.JLabel lblDe;
    private javax.swing.JLabel lblKho;
    private javax.swing.JLabel lblMaCode;
    private javax.swing.JLabel lblMaDT;
    private javax.swing.JLabel lblNgayTao;
    private javax.swing.JLabel lblSoLanThi;
    private javax.swing.JLabel lblTB;
    private javax.swing.JLabel lblTenDeThi;
    private javax.swing.JLabel lblThoiGianLamBai;
    private javax.swing.JLabel lblTinhTrang;
    private javax.swing.JLabel lblXemDT;
    private javax.swing.JTextField txtChuDe;
    private javax.swing.JTextField txtDe;
    private javax.swing.JTextField txtKho;
    private javax.swing.JTextField txtMaCode;
    private javax.swing.JTextField txtMaDT;
    private javax.swing.JTextField txtMaND3;
    private javax.swing.JTextField txtNgayTao;
    private javax.swing.JTextField txtSoLanThi;
    private javax.swing.JTextField txtTB;
    private javax.swing.JTextField txtTenDeThi;
    private javax.swing.JTextField txtThoiGianLamBai;
    // End of variables declaration//GEN-END:variables

    public void setThongTinDeThi(DeThiDTO deThi) {
        txtMaDT.setText(String.valueOf(deThi.getTestID()));
        txtMaCode.setText(deThi.getTestCode());
        txtTenDeThi.setText(deThi.getTestTitle());
        txtThoiGianLamBai.setText(String.valueOf(deThi.getTestTime()));
        txtChuDe.setText(String.valueOf(deThi.getTopicID()));
        txtSoLanThi.setText(String.valueOf(deThi.getTestLimit()));
        txtDe.setText(String.valueOf(deThi.getNum_easy()));
        txtTB.setText(String.valueOf(deThi.getNum_medium()));
        txtKho.setText(String.valueOf(deThi.getNum_diff()));
        txtNgayTao.setText(deThi.getTestDate()); 
        String tinhTrang = deThi.getTestStatus().equals("1") ? "Đang hoạt động" : "Ngưng hoạt động";
        cmbTinhTrang.setSelectedItem(tinhTrang);
    }
}
